
###########################################
# Create the Prevoty database and user
###########################################
# mysql -h localhost -u root mysql -p
# CREATE DATABASE `prevoty_db`;
# CREATE USER 'prevoty_usr'@'%' IDENTIFIED BY 'prevoty_pwd';
# GRANT ALL PRIVILEGES ON `prevoty_db`.* TO 'prevoty_usr'@'%' WITH GRANT OPTION;
# FLUSH PRIVILEGES;
# EXIT

###########################################
# Delete the Prevoty database and user
###########################################
# mysql -h localhost -u root mysql -p
# REVOKE USAGE ON *.* FROM 'prevoty_usr'@'%';
# REVOKE ALL PRIVILEGES ON `prevoty_db`.* FROM 'prevoty_usr'@'%';
# DROP USER 'prevoty_usr'@'%';
# DROP DATABASE `prevoty_db`;
# FLUSH PRIVILEGES;
# EXIT

###########################################
# Run MySQL script from file
###########################################
# mysql -h localhost -u prevoty_usr prevoty_db -p < ./prevoty_script.sql

###########################################
# Drop the Prevoty table
###########################################
# mysql -h localhost -u prevoty_usr prevoty_db -p
DROP TABLE prevoty_event;

###########################################
# Path Traversal - Whitelisted Paths
###########################################
# SELECT path
# FROM prevoty_event
# WHERE ((category = "Path Traversal") AND (severity <> "informational"))
# GROUP BY path;

###########################################
# Cross-Site Request Forgery - Permitted Origins
###########################################
# SELECT mode, action, severity, dest_host, SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(http_referrer, '/', 3), '://', -1), '/', 1), '?', 1) AS "http_referrer (domain)", SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(url, '/', 3), '://', -1), '/', 1), '?', 1) AS "url (domain)"
# FROM prevoty_event
# WHERE ((category = "Cross-Site Request Forgery") AND (severity <> "informational") AND (validation_message = "mismatched origin"))
# ORDER BY action, severity;

###########################################
# Cross-Site Request Forgery - Generation & Validation Whitelist
###########################################
# SELECT uri_path
# FROM prevoty_event 
# WHERE ((category = "Cross-Site Request Forgery") AND (severity <> "informational") AND (validation_message = "token is missing") AND (http_method = "POST"))
# GROUP BY uri_path;

###########################################
# Content Injection - Ignored URL Paths
###########################################
# SELECT uri_path
# FROM prevoty_event 
# WHERE ((category = "Cross-Site Scripting") AND (severity <> "informational")))
# GROUP BY uri_path;

###########################################
# Create the Prevoty table
###########################################
CREATE TABLE prevoty_event (
	app_version VARCHAR(10),
	content_requests INTEGER,
	token_requests INTEGER,
	javascript_tags INTEGER,
	invalid_tags INTEGER,
	mode VARCHAR(10),
	output TEXT,
	path VARCHAR(300),
	http_method VARCHAR(10),
	uri_path VARCHAR(900),
	invalid_protocols INTEGER,
	session_creation_time DATE,
	action VARCHAR(10),
	PT_requests INTEGER,
	dest_port VARCHAR(25),
	app VARCHAR(100),
	payload_type VARCHAR(100),
	query VARCHAR(300),
	version VARCHAR(25),
	input TEXT,
	uri_query TEXT,
	validation_message VARCHAR(100),
	tags_balanced INTEGER,
	dest_ip VARCHAR(25),
	transformations INTEGER,
	name VARCHAR(150),
	http_referrer TEXT,
	query_requests INTEGER,
	stack_trace TEXT,
	CI_requests INTEGER,
	vm_runtime_version VARCHAR(10),
	access_type VARCHAR(10),
	result_compliant VARCHAR(10),
	skip VARCHAR(10),
	statements TEXT,
	result_block VARCHAR(10),
	cookies TEXT,
	forwarded_for VARCHAR(25),
	http_user_agent VARCHAR(200),
	javascript_attributes INTEGER,
	src_ip VARCHAR(25),
	valid VARCHAR(10),
	session_is_new VARCHAR(10),
	time_span INTEGER,
	db_vendor VARCHAR(20),
	http_content_type VARCHAR(200),
	engine VARCHAR(10),
	line_number INTEGER,
	vendor VARCHAR(20),
	app_lang VARCHAR(10),
	unique_requests INTEGER,
	direction VARCHAR(10),
	timestamp DATE,
	severity VARCHAR(15),
	product VARCHAR(10),
	product_version VARCHAR(10),
	os VARCHAR(100),
	os_version VARCHAR(100),
	transport VARCHAR(10),
	script_name VARCHAR(200),
	session_attributes VARCHAR(100),
	invalid_attributes INTEGER,
	url TEXT,
	src_port INTEGER,
	processed VARCHAR(10),
	dest_host VARCHAR(100),
	javascript_protocols INTEGER,
	category VARCHAR(30),
	user VARCHAR(50));

###########################################
# Create the Prevoty indexes
###########################################
CREATE INDEX idx_mode ON prevoty_event (mode);
CREATE INDEX idx_action ON prevoty_event (action);
CREATE INDEX idx_query ON prevoty_event (query);
CREATE INDEX idx_name ON prevoty_event (name);
CREATE INDEX idx_severity ON prevoty_event (severity);
CREATE INDEX idx_processed ON prevoty_event (processed);
CREATE INDEX idx_category ON prevoty_event (category);

###########################################
# Fill the Prevoty event table
###########################################
Did not find the key: "configuration"
Did not find the key: "configuration_loaded"
Did not find the key: "configuration_source"
# Record count: 1
INSERT INTO prevoty_event (
	app,
	app_lang,
	app_version,
	category,
	os,
	os_version,
	product,
	product_version,
	severity,
	timestamp,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Configuration",
	"Mac OS X",
	"10.14.5",
	"RASP",
	"3.10.3",
	"informational",
	(STR_TO_DATE("Jul 17 2019 19:55:32 UTC", "%b %e %Y %H:%i:%S UTC")),
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
Did not find the key: "algorithm"
# Record count: 2
INSERT INTO prevoty_event (
	action,
	app,
	app_lang,
	app_version,
	category,
	engine,
	line_number,
	mode,
	os,
	os_version,
	product,
	product_version,
	script_name,
	severity,
	stack_trace,
	timestamp,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Weak Cryptography",
	"cryptography",
	"304",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"RASP",
	"3.10.3",
	"Security.java",
	"high",
	"com.mysql.jdbc.Security com.mysql.jdbc.authentication.MysqlNativePasswordPlugin com.mysql.jdbc.MysqlIO com.mysql.jdbc.MysqlIO com.mysql.jdbc.ConnectionImpl com.mysql.jdbc.ConnectionImpl com.mysql.jdbc.ConnectionImpl com.mysql.jdbc.ConnectionImpl com.mysql.jdbc.JDBC4Connection sun.reflect.NativeConstructorAccessorImpl sun.reflect.NativeConstructorAccessorImpl sun.reflect.DelegatingConstructorAccessorImpl java.lang.reflect.Constructor com.mysql.jdbc.Util com.mysql.jdbc.ConnectionImpl com.mysql.jdbc.NonRegisteringDriver com.mysql.jdbc.jdbc2.optional.MysqlDataSource com.mysql.jdbc.jdbc2.optional.MysqlDataSource com.mysql.jdbc.jdbc2.optional.MysqlDataSource com.acme.core.MySQLStock com.acme.core.SearchServlet javax.servlet.GenericServlet org.apache.catalina.core.StandardWrapper org.apache.catalina.core.StandardWrapper org.apache.catalina.core.StandardWrapper org.apache.catalina.core.StandardContext org.apache.catalina.core.StandardContext org.apache.catalina.util.LifecycleBase org.apache.catalina.core.ContainerBase org.apache.catalina.core.ContainerBase org.apache.catalina.core.StandardHost org.apache.catalina.startup.HostConfig org.apache.catalina.startup.HostConfig$DeployDirectory java.util.concurrent.Executors$RunnableAdapter java.util.concurrent.FutureTask java.util.concurrent.ThreadPoolExecutor java.util.concurrent.ThreadPoolExecutor$Worker java.lang.Thread",
	(STR_TO_DATE("Jul 17 2019 19:55:35 UTC", "%b %e %Y %H:%i:%S UTC")),
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
Did not find the key: "shared_temporary_directory"
# Record count: 3
INSERT INTO prevoty_event (
	access_type,
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_method,
	http_user_agent,
	mode,
	os,
	os_version,
	path,
	product,
	product_version,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	stack_trace,
	timestamp,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"read",
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Path Traversal",
	"{'splunkweb_csrf_token_8000':'7507278349945591430'}",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"path",
	"GET",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/security/blacklisted.certs",
	"RASP",
	"3.10.3",
	"{}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"true",
	"informational",
	"0:0:0:0:0:0:0:1",
	"55482",
	"com.prevoty.pathtraversal.PathTraversalShim.logResult(PathTraversalShim.java:209) com.prevoty.pathtraversal.PathTraversalShim.validatePath(PathTraversalShim.java:130) com.prevoty.pathtraversal.PathTraversalShim.validateFilePath(PathTraversalShim.java:141) java.io.FileInputStream.<init>(FileInputStream.java:123) sun.security.util.UntrustedCertificates$1.run(UntrustedCertificates.java:59) sun.security.util.UntrustedCertificates$1.run(UntrustedCertificates.java:54) java.security.AccessController.doPrivileged(Native Method) sun.security.util.UntrustedCertificates.<clinit>(UntrustedCertificates.java:54) sun.security.provider.certpath.UntrustedChecker.check(UntrustedChecker.java:78) java.security.cert.PKIXCertPathChecker.check(PKIXCertPathChecker.java:176) sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:148) sun.security.validator.Validator.validate(Validator.java:262) sun.security.validator.Validator.validate(Validator.java:238) sun.security.validator.Validator.validate(Validator.java:207) javax.crypto.JarVerifier.isTrusted(JarVerifier.java:610) javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:530) javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363) javax.crypto.JarVerifier.verify(JarVerifier.java:289) javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164) javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190) javax.crypto.JceSecurity.canUseProvider(JceSecurity.java:204) javax.crypto.Mac.getInstance(Mac.java:176) com.prevoty.csrf.Filter$TokenGenerator.hmac(Filter.java:596) com.prevoty.csrf.Filter$TokenGenerator.<init>(Filter.java:468) com.prevoty.csrf.Filter.doFilter(Filter.java:254) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.content.Filter.handleRequest(Filter.java:486) com.prevoty.content.Filter.doFilter(Filter.java:213) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.reporting.Filter.doFilter(Filter.java:114) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.servlet.filter.PrevotyFilterChain.doPrevotyFilterChain(PrevotyFilterChain.java:150) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:57) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter.doFilter(DoNothingFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) java.lang.Thread.run(Thread.java:748)",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"tcp",
	"/acme-webapp-java/",
	"http://localhost:8080/acme-webapp-java/",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
Did not find the key: "shared_temporary_directory"
# Record count: 4
INSERT INTO prevoty_event (
	access_type,
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_method,
	http_user_agent,
	mode,
	os,
	os_version,
	path,
	product,
	product_version,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	stack_trace,
	timestamp,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"read",
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Path Traversal",
	"{'splunkweb_csrf_token_8000':'7507278349945591430'}",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"path",
	"GET",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/security/cacerts",
	"RASP",
	"3.10.3",
	"{}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"true",
	"informational",
	"0:0:0:0:0:0:0:1",
	"55482",
	"com.prevoty.pathtraversal.PathTraversalShim.logResult(PathTraversalShim.java:209) com.prevoty.pathtraversal.PathTraversalShim.validatePath(PathTraversalShim.java:130) com.prevoty.pathtraversal.PathTraversalShim.validateFilePath(PathTraversalShim.java:141) java.io.FileInputStream.<init>(FileInputStream.java:123) sun.security.util.AnchorCertificates$1.run(AnchorCertificates.java:60) sun.security.util.AnchorCertificates$1.run(AnchorCertificates.java:52) java.security.AccessController.doPrivileged(Native Method) sun.security.util.AnchorCertificates.<clinit>(AnchorCertificates.java:52) sun.security.provider.certpath.AlgorithmChecker.checkFingerprint(AlgorithmChecker.java:214) sun.security.provider.certpath.AlgorithmChecker.<init>(AlgorithmChecker.java:164) sun.security.provider.certpath.AlgorithmChecker.<init>(AlgorithmChecker.java:118) sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:157) sun.security.validator.Validator.validate(Validator.java:262) sun.security.validator.Validator.validate(Validator.java:238) sun.security.validator.Validator.validate(Validator.java:207) javax.crypto.JarVerifier.isTrusted(JarVerifier.java:610) javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:530) javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363) javax.crypto.JarVerifier.verify(JarVerifier.java:289) javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164) javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190) javax.crypto.JceSecurity.canUseProvider(JceSecurity.java:204) javax.crypto.Mac.getInstance(Mac.java:176) com.prevoty.csrf.Filter$TokenGenerator.hmac(Filter.java:596) com.prevoty.csrf.Filter$TokenGenerator.<init>(Filter.java:468) com.prevoty.csrf.Filter.doFilter(Filter.java:254) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.content.Filter.handleRequest(Filter.java:486) com.prevoty.content.Filter.doFilter(Filter.java:213) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.reporting.Filter.doFilter(Filter.java:114) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.servlet.filter.PrevotyFilterChain.doPrevotyFilterChain(PrevotyFilterChain.java:150) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:57) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter.doFilter(DoNothingFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) java.lang.Thread.run(Thread.java:748)",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"tcp",
	"/acme-webapp-java/",
	"http://localhost:8080/acme-webapp-java/",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
Did not find the key: "shared_temporary_directory"
# Record count: 5
INSERT INTO prevoty_event (
	access_type,
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_method,
	http_user_agent,
	mode,
	os,
	os_version,
	path,
	product,
	product_version,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	stack_trace,
	timestamp,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"read",
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Path Traversal",
	"{'splunkweb_csrf_token_8000':'7507278349945591430'}",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"path",
	"GET",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"/opt/apache-tomcat-8.5.40/webapps/acme-webapp-java/index.jsp",
	"RASP",
	"3.10.3",
	"{}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"true",
	"informational",
	"0:0:0:0:0:0:0:1",
	"55482",
	"com.prevoty.pathtraversal.PathTraversalShim.logResult(PathTraversalShim.java:209) com.prevoty.pathtraversal.PathTraversalShim.validatePath(PathTraversalShim.java:130) com.prevoty.pathtraversal.PathTraversalShim.validateFilePath(PathTraversalShim.java:141) java.io.FileInputStream.<init>(FileInputStream.java:123) java.io.FileInputStream.<init>(FileInputStream.java:93) sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90) sun.net.www.protocol.file.FileURLConnection.initializeHeaders(FileURLConnection.java:110) sun.net.www.protocol.file.FileURLConnection.getLastModified(FileURLConnection.java:178) org.apache.jasper.JspCompilationContext.getLastModified(JspCompilationContext.java:396) org.apache.jasper.JspCompilationContext.getLastModified(JspCompilationContext.java:368) org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:470) org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:424) org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:588) org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399) org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) javax.servlet.http.HttpServlet.serviceInternal(HttpServlet.java:742) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.ServletInvoker.invokeServiceInternal(ServletInvoker.java:46) com.prevoty.servlet.agent.ServletProcessor.processServletRequest(ServletProcessor.java:47) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) javax.servlet.http.HttpServlet.service(HttpServlet.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.tomcat.websocket.server.WsFilter.doFilterInternalPrevoty(WsFilter.java:52) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter2.doFilterInternalPrevoty(DoNothingFilter2.java:23) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter2.doFilter(DoNothingFilter2.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter.doFilterInternalPrevoty(DoNothingFilter.java:23) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:136) com.prevoty.csrf.Filter.doFilter(Filter.java:314) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.content.Filter.handleRequest(Filter.java:486) com.prevoty.content.Filter.doFilter(Filter.java:213) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.reporting.Filter.doFilter(Filter.java:114) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.servlet.filter.PrevotyFilterChain.doPrevotyFilterChain(PrevotyFilterChain.java:150) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:57) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter.doFilter(DoNothingFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) java.lang.Thread.run(Thread.java:748)",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"tcp",
	"/acme-webapp-java/",
	"http://localhost:8080/acme-webapp-java/",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
Did not find the key: "shared_temporary_directory"
# Record count: 6
INSERT INTO prevoty_event (
	access_type,
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_method,
	http_user_agent,
	mode,
	os,
	os_version,
	path,
	product,
	product_version,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	stack_trace,
	timestamp,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"read",
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Path Traversal",
	"{'splunkweb_csrf_token_8000':'7507278349945591430'}",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"path",
	"GET",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"/opt/apache-tomcat-8.5.40/work/Catalina/localhost/acme-webapp-java/org/apache/jsp/index_jsp.class",
	"RASP",
	"3.10.3",
	"{}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"true",
	"informational",
	"0:0:0:0:0:0:0:1",
	"55482",
	"com.prevoty.pathtraversal.PathTraversalShim.logResult(PathTraversalShim.java:209) com.prevoty.pathtraversal.PathTraversalShim.validatePath(PathTraversalShim.java:130) com.prevoty.pathtraversal.PathTraversalShim.validateFilePath(PathTraversalShim.java:141) java.io.FileInputStream.<init>(FileInputStream.java:123) sun.misc.URLClassPath$FileLoader$1.getInputStream(URLClassPath.java:1288) sun.misc.Resource.cachedInputStream(Resource.java:77) sun.misc.Resource.getByteBuffer(Resource.java:160) java.net.URLClassLoader.defineClass(URLClassLoader.java:454) java.net.URLClassLoader.access$100(URLClassLoader.java:73) java.net.URLClassLoader$1.run(URLClassLoader.java:368) java.net.URLClassLoader$1.run(URLClassLoader.java:362) java.security.AccessController.doPrivileged(Native Method) java.net.URLClassLoader.findClass(URLClassLoader.java:361) org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:129) org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:60) org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:159) org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:192) org.apache.jasper.servlet.JspServletWrapper.getDependants(JspServletWrapper.java:331) org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:490) org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:424) org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:588) org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399) org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) javax.servlet.http.HttpServlet.serviceInternal(HttpServlet.java:742) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.ServletInvoker.invokeServiceInternal(ServletInvoker.java:46) com.prevoty.servlet.agent.ServletProcessor.processServletRequest(ServletProcessor.java:47) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) javax.servlet.http.HttpServlet.service(HttpServlet.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.tomcat.websocket.server.WsFilter.doFilterInternalPrevoty(WsFilter.java:52) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter2.doFilterInternalPrevoty(DoNothingFilter2.java:23) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter2.doFilter(DoNothingFilter2.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter.doFilterInternalPrevoty(DoNothingFilter.java:23) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:136) com.prevoty.csrf.Filter.doFilter(Filter.java:314) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.content.Filter.handleRequest(Filter.java:486) com.prevoty.content.Filter.doFilter(Filter.java:213) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.reporting.Filter.doFilter(Filter.java:114) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.servlet.filter.PrevotyFilterChain.doPrevotyFilterChain(PrevotyFilterChain.java:150) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:57) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter.doFilter(DoNothingFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) java.lang.Thread.run(Thread.java:748)",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"tcp",
	"/acme-webapp-java/",
	"http://localhost:8080/acme-webapp-java/",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
Did not find the key: "shared_temporary_directory"
# Record count: 7
INSERT INTO prevoty_event (
	access_type,
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_method,
	http_user_agent,
	mode,
	os,
	os_version,
	path,
	product,
	product_version,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	stack_trace,
	timestamp,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"read",
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Path Traversal",
	"{'splunkweb_csrf_token_8000':'7507278349945591430'}",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"path",
	"GET",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"/opt/apache-tomcat-8.5.40/webapps/acme-webapp-java/headers.jsp",
	"RASP",
	"3.10.3",
	"{}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"true",
	"informational",
	"0:0:0:0:0:0:0:1",
	"55482",
	"com.prevoty.pathtraversal.PathTraversalShim.logResult(PathTraversalShim.java:209) com.prevoty.pathtraversal.PathTraversalShim.validatePath(PathTraversalShim.java:130) com.prevoty.pathtraversal.PathTraversalShim.validateFilePath(PathTraversalShim.java:141) java.io.FileInputStream.<init>(FileInputStream.java:123) java.io.FileInputStream.<init>(FileInputStream.java:93) sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90) sun.net.www.protocol.file.FileURLConnection.initializeHeaders(FileURLConnection.java:110) sun.net.www.protocol.file.FileURLConnection.getLastModified(FileURLConnection.java:178) org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:521) org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:424) org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:588) org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399) org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) javax.servlet.http.HttpServlet.serviceInternal(HttpServlet.java:742) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.ServletInvoker.invokeServiceInternal(ServletInvoker.java:46) com.prevoty.servlet.agent.ServletProcessor.processServletRequest(ServletProcessor.java:47) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) javax.servlet.http.HttpServlet.service(HttpServlet.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.tomcat.websocket.server.WsFilter.doFilterInternalPrevoty(WsFilter.java:52) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter2.doFilterInternalPrevoty(DoNothingFilter2.java:23) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter2.doFilter(DoNothingFilter2.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter.doFilterInternalPrevoty(DoNothingFilter.java:23) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:136) com.prevoty.csrf.Filter.doFilter(Filter.java:314) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.content.Filter.handleRequest(Filter.java:486) com.prevoty.content.Filter.doFilter(Filter.java:213) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.reporting.Filter.doFilter(Filter.java:114) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.servlet.filter.PrevotyFilterChain.doPrevotyFilterChain(PrevotyFilterChain.java:150) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:57) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter.doFilter(DoNothingFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) java.lang.Thread.run(Thread.java:748)",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"tcp",
	"/acme-webapp-java/",
	"http://localhost:8080/acme-webapp-java/",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
# Record count: 8
INSERT INTO prevoty_event (
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_content_type,
	http_method,
	http_referrer,
	http_user_agent,
	input,
	invalid_attributes,
	invalid_protocols,
	invalid_tags,
	javascript_attributes,
	javascript_protocols,
	javascript_tags,
	mode,
	os,
	os_version,
	output,
	payload_type,
	product,
	product_version,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	tags_balanced,
	timestamp,
	transformations,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"HTML Injection",
	"{'ANTI-CSRF-TOKEN':'6ad40ba74ef7d708b53051fdcc84813c-5de4a3c9481f8f28cbdd74300aa021a8258a6bbeffb29d7ea8320c5495b88ac3-1563396939-4afae123b83f5085d58576be216481db5966475faf09d5026ce9ae3bf0dd9e33','splunkweb_csrf_token_8000':'7507278349945591430','JSESSIONID':'E8804785D851896CE3C4CA6E882A9E01'}",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"content",
	"application/x-www-form-urlencoded; charset=UTF-8",
	"POST",
	"http://localhost:8080/acme-webapp-java/",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"symbol=%3Cstrike%3EHTMLi%3C%2Fstrike%3E",
	"0",
	"0",
	"2",
	"0",
	"0",
	"0",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"symbol=",
	"body_parameter_string",
	"RASP",
	"3.10.3",
	"{'ACME Username':'acme_default_user','ACME Role':'user'}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"false",
	"high",
	"0:0:0:0:0:0:0:1",
	"55491",
	"0",
	(STR_TO_DATE("Jul 17 2019 19:56:01 UTC", "%b %e %Y %H:%i:%S UTC")),
	"2",
	"tcp",
	"/acme-webapp-java/search",
	"http://localhost:8080/acme-webapp-java/search",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
Did not find the key: "shared_temporary_directory"
# Record count: 9
INSERT INTO prevoty_event (
	access_type,
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_content_type,
	http_method,
	http_referrer,
	http_user_agent,
	mode,
	os,
	os_version,
	path,
	product,
	product_version,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	stack_trace,
	timestamp,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"read",
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"Path Traversal",
	"{'ANTI-CSRF-TOKEN':'6ad40ba74ef7d708b53051fdcc84813c-5de4a3c9481f8f28cbdd74300aa021a8258a6bbeffb29d7ea8320c5495b88ac3-1563396939-4afae123b83f5085d58576be216481db5966475faf09d5026ce9ae3bf0dd9e33','splunkweb_csrf_token_8000':'7507278349945591430','JSESSIONID':'E8804785D851896CE3C4CA6E882A9E01'}",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"path",
	"application/x-www-form-urlencoded; charset=UTF-8",
	"POST",
	"http://localhost:8080/acme-webapp-java/",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"/opt/apache-tomcat-8.5.40/webapps/acme-webapp-java/WEB-INF/classes/com/acme/core/SearchResult.class",
	"RASP",
	"3.10.3",
	"{'ACME Username':'acme_default_user','ACME Role':'user'}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"false",
	"informational",
	"0:0:0:0:0:0:0:1",
	"55491",
	"com.prevoty.pathtraversal.PathTraversalShim.logResult(PathTraversalShim.java:209) com.prevoty.pathtraversal.PathTraversalShim.validatePath(PathTraversalShim.java:130) com.prevoty.pathtraversal.PathTraversalShim.validateFilePath(PathTraversalShim.java:141) java.io.FileInputStream.<init>(FileInputStream.java:123) org.apache.catalina.webresources.FileResource.getContent(FileResource.java:210) org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2325) org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:859) org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333) org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185) com.acme.core.SearchServlet.doGet(SearchServlet.java:163) com.acme.core.SearchServlet.doPost(SearchServlet.java:253) javax.servlet.http.HttpServlet.service(HttpServlet.java:661) javax.servlet.http.HttpServlet.serviceInternal(HttpServlet.java:742) sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.ServletInvoker.invokeServiceInternal(ServletInvoker.java:46) com.prevoty.servlet.agent.ServletProcessor.processServletRequest(ServletProcessor.java:47) sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) javax.servlet.http.HttpServlet.service(HttpServlet.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.tomcat.websocket.server.WsFilter.doFilterInternalPrevoty(WsFilter.java:52) sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter2.doFilterInternalPrevoty(DoNothingFilter2.java:23) sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61) sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter2.doFilter(DoNothingFilter2.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) com.acme.core.DoNothingFilter.doFilterInternalPrevoty(DoNothingFilter.java:23) sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:136) com.prevoty.csrf.Filter.doFilter(Filter.java:206) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.content.Filter.handleRequest(Filter.java:486) com.prevoty.content.Filter.doFilter(Filter.java:213) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.reporting.Filter.doFilter(Filter.java:114) com.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130) com.prevoty.servlet.filter.PrevotyFilterChain.doPrevotyFilterChain(PrevotyFilterChain.java:150) com.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:57) sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.acme.core.DoNothingFilter.doFilter(DoNothingFilter.java) org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) java.lang.Thread.run(Thread.java:748)",
	(STR_TO_DATE("Jul 17 2019 19:56:01 UTC", "%b %e %Y %H:%i:%S UTC")),
	"tcp",
	"/acme-webapp-java/search",
	"http://localhost:8080/acme-webapp-java/search",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
# Record count: 10
INSERT INTO prevoty_event (
	action,
	app,
	app_lang,
	app_version,
	category,
	cookies,
	db_vendor,
	dest_host,
	dest_ip,
	dest_port,
	direction,
	engine,
	http_content_type,
	http_method,
	http_referrer,
	http_user_agent,
	line_number,
	mode,
	os,
	os_version,
	processed,
	product,
	product_version,
	query,
	result_block,
	result_compliant,
	script_name,
	session_attributes,
	session_creation_time,
	session_is_new,
	severity,
	src_ip,
	src_port,
	stack_trace,
	statements,
	timestamp,
	transport,
	uri_path,
	url,
	user,
	vendor,
	vm_runtime_version )
VALUES (
	"allowed",
	"acme-java_monitor",
	"java",
	"1.8.0_181",
	"normal",
	"{'ANTI-CSRF-TOKEN':'6ad40ba74ef7d708b53051fdcc84813c-5de4a3c9481f8f28cbdd74300aa021a8258a6bbeffb29d7ea8320c5495b88ac3-1563396939-4afae123b83f5085d58576be216481db5966475faf09d5026ce9ae3bf0dd9e33','splunkweb_csrf_token_8000':'7507278349945591430','JSESSIONID':'E8804785D851896CE3C4CA6E882A9E01'}",
	"mysql",
	"localhost",
	"0:0:0:0:0:0:0:1",
	"8080",
	"inbound",
	"query",
	"application/x-www-form-urlencoded; charset=UTF-8",
	"POST",
	"http://localhost:8080/acme-webapp-java/",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
	"748",
	"monitor",
	"Mac OS X",
	"10.14.5",
	"true",
	"RASP",
	"3.10.3",
	"select name from stocks where name='<strike>htmli</strike>'",
	"false",
	"false",
	"Thread.java",
	"{'ACME Username':'acme_default_user','ACME Role':'user'}",
	(STR_TO_DATE("Jul 17 2019 19:55:38 UTC", "%b %e %Y %H:%i:%S UTC")),
	"false",
	"informational",
	"0:0:0:0:0:0:0:1",
	"55491",
	"com.prevoty.query.SQLQueryProcessor.processStatement(SQLQueryProcessor.java:216)\ncom.mysql.jdbc.StatementImpl.execute(StatementImpl.java)\ncom.mysql.jdbc.StatementImpl.execute(StatementImpl.java:748)\ncom.acme.core.BaseStock.findSymbol(BaseStock.java:60)\ncom.acme.core.SearchServlet.doGet(SearchServlet.java:162)\ncom.acme.core.SearchServlet.doPost(SearchServlet.java:253)\njavax.servlet.http.HttpServlet.service(HttpServlet.java:661)\njavax.servlet.http.HttpServlet.serviceInternal(HttpServlet.java:742)\nsun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\ncom.prevoty.servlet.agent.ServletInvoker.invokeServiceInternal(ServletInvoker.java:46)\ncom.prevoty.servlet.agent.ServletProcessor.processServletRequest(ServletProcessor.java:47)\nsun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\njavax.servlet.http.HttpServlet.service(HttpServlet.java)\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\norg.apache.tomcat.websocket.server.WsFilter.doFilterInternalPrevoty(WsFilter.java:52)\nsun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\ncom.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50)\ncom.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61)\nsun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\norg.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java)\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\ncom.acme.core.DoNothingFilter2.doFilterInternalPrevoty(DoNothingFilter2.java:23)\nsun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\ncom.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50)\ncom.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:61)\nsun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\ncom.acme.core.DoNothingFilter2.doFilter(DoNothingFilter2.java)\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\ncom.acme.core.DoNothingFilter.doFilterInternalPrevoty(DoNothingFilter.java:23)\nsun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\ncom.prevoty.servlet.agent.FilterInvoker.invokeDoFilterInternal(FilterInvoker.java:50)\ncom.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:136)\ncom.prevoty.csrf.Filter.doFilter(Filter.java:206)\ncom.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130)\ncom.prevoty.content.Filter.handleRequest(Filter.java:486)\ncom.prevoty.content.Filter.doFilter(Filter.java:213)\ncom.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130)\ncom.prevoty.reporting.Filter.doFilter(Filter.java:114)\ncom.prevoty.servlet.filter.PrevotyFilterChain.doFilter(PrevotyFilterChain.java:130)\ncom.prevoty.servlet.filter.PrevotyFilterChain.doPrevotyFilterChain(PrevotyFilterChain.java:150)\ncom.prevoty.servlet.agent.ServletFilterProcessor.processFilterRequest(ServletFilterProcessor.java:57)\nsun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\ncom.acme.core.DoNothingFilter.doFilter(DoNothingFilter.java)\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\norg.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)\norg.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\norg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)\norg.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)\norg.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)\norg.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\norg.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\norg.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)\norg.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\norg.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)\norg.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)\norg.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\njava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\njava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\norg.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\njava.lang.Thread.run(Thread.java:748)",
	"[{'violations':{'row_create_violations':[],'admin_violation':false,'function_violations':[],'column_update_violations':[],'violations_count':1,'union_violations':[],'row_delete_violations':[],'subquery_violations':[],'column_read_violations':[{'database':'acme_db','column':'name','table':'stocks'}],'join_violations':[]},'intelligence':{'joins':[],'function_calls':[],'unions':[],'has_admin':false,'subqueries':[],'column_reads':[{'database':'acme_db','column':'name','table':'stocks'}],'column_updates':[],'row_creates':[],'sanitized_statement':'SELECT NAME FROM stocks WHERE NAME = 'XXXXXXXXXXXXXXXXXXXXXX'','has_comment':false,'hashed_statement':'d6d74202e9da8830b828760fdd7e5957','comparison_types':{'static':false,'tautology':false,'dynamic':true,'contradiction':false},'row_deletes':[],'statement_type':'select'}}]",
	(STR_TO_DATE("Jul 17 2019 19:56:02 UTC", "%b %e %Y %H:%i:%S UTC")),
	"tcp",
	"/acme-webapp-java/search",
	"http://localhost:8080/acme-webapp-java/search",
	"percy.rotteveel",
	"Prevoty",
	"25.181-b13" );
